name: Maven Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up JDK 17 based on your needs
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Build the Maven project
      - name: Build with Maven
        run: mvn clean package

      # # Upload artifact to JFrog Artifactory
      # - name: Deploy to JFrog Artifactory
      #   uses: jfrog/setup-jfrog-cli@v2
      #   with:
      #     version: latest

      # - name: Configure JFrog CLI
      #   run: jfrog rt config --url=$ARTIFACTORY_URL --user=$ARTIFACTORY_USERNAME --password=$ARTIFACTORY_PASSWORD

      # # Upload the artifact to JFrog Artifactory
      # - name: Upload to Artifactory
      #   run: jfrog rt u "target/*.jar" "my-repo-name/path/to/destination/"
      #   env:
      #     ARTIFACTORY_URL: ${{ secrets.ARTIFACTORY_URL }}
      #     ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
      #     ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
